### PR TITLE
xCode beta 5 and multi-dates selection

### PR DESCRIPTION
**Pull request by workingDog**
compatibility with xCode beta 5
added selectedDates: [Date] to RKManager
added a new mode=3 for the selectedDates
some other bits

### CODE REVIEW

**Comment by workingDog** [comment]
new update

**Comment by workingDog** [comment]
Hi Raffi,

I was in need of a time selection in my app, so I added the functionality to RKCalendar.

https://github.com/workingDog/RKCalendar <https://github.com/workingDog/RKCalendar>

Could you have a look at it with the view to a merge if this function is agreeable.

Ringo

**Comment by lburris57** [comment]
Hello Raffi,

I would like to incorporate your calendar code in a project that I am working on to learn SwiftUI.  Since I am still somewhat in the learning stage, I'm not exactly sure how to do this.  Would it be possible to point me in the right direction?  I'm doing things a little differently than your examples.  I'm don't want to use a sheet.  I want the calendar to be in a list at the top half of a screen and have the selected date display a list of items for that particular day in the bottom half of the screen.  I'm pretty sure that I can handle that part of it.  I just wanted to be sure that I am displaying the correct months since it needs to be able to view both previous and future months.  Any guidance you could give would be greatly appreciated.  You can email me at lburris@mac.com if you'd like to help.

Many thanks,
Larry Burris

**Comment by workingDog** [comment]
Hi Larry,

To show RKViewController without a sheet, just use it on its own as in the example below.
The RKViewController months are already in a List, so there is no need for another one.
To show the months/days you want to display simply adjust, minimumDate and maximumDate.
For example:
 
 ```
struct ContentView2: View {
     @State var isPresented = false  // not relevant for this example
     var rkManager1 = RKManager(calendar: Calendar.current,
                     minimumDate: Date().addingTimeInterval(-60*60*24*182), // ~6 months before today
                     maximumDate: Date().addingTimeInterval(60*60*24*182),  // ~6 months after today
                     mode: 0)
     var body: some View {
         Group {
             VStack {
                 RKViewController(isPresented: self.$isPresented, rkManager: rkManager1)
             }
             List {
                 Text("item1")
                 Text("item2")
                 Text("item3")
                 Text("item4")
                 Text("item5")
                 Text("item6")
             }
         }
     }
 }
```

**Comment by lburris57** [comment]
Thanks so much for getting back to me.  I believe that I have a handle on it now.  I wasn’t expecting it to be this easy!!

**Comment by lburris57** [comment]
Raffi,

Please excuse my ignorance, but I’ve looked at your code and I’m not seeing exactly how you are detecting the date selection.  I see the code that references the manager for the selected date but I’m not seeing what triggers it.  I’m sure that it’s going to be something staring me right in the face but I’m just not seeing it at 4 AM.  I have successfully incorporated the calendar into my code.  I’m always going to be displaying full months from October till June so it was easy to calculate the date information.  I just need to detect the date selection and my problems will be solved.

I thank you again for your help!  Your calendar rocks!

~ Larry

**Comment by workingDog** [comment]
Hi Larry,

In RKMonth a TapGesture is attached to a RKCell, so when a tap event is detected,
 .onTapGesture { self.dateTapped(date: column) is called.
 
In dateTapped() the rkManager.selectedDate is updated.
 
 Now rkManager is an observedObject, which means you don't "detect" 
 where the date selection is done. You simply use rkManager.selectedDate, and by magic 
 the value is updated for you wherever you have it in your code and the views will be updated as well.
 
 Ringo

**Comment by lburris57** [comment]
Great!!  Thanks for the help!!

**Comment by lburris57** [comment]
Hello,

I appreciate you getting back to me last month!  I have everything working exactly as I want with one small exception.  Instead of displaying the calendars in a list, would it be possible to to display one calendar at a time inside a drag gesture going left/right?  Since I am using the calendar in the top half of a screen, it’s impossible to display a single month without some overlap of another month because not all months have the same number of rows in them.  My plan is to split the screen to the max size of a single calendar and let the user select the calendar by dragging from left/right.  Since each calendar is the same width, this seems to be the best solution for me.

Would it be possible to add that option to your calendar code?  Or maybe provide a previous/next button to allow the user to select one month at a time within the constraints of the number of months in the list?

Any guidance you could give would be greatly appreciated!

Many thanks,
Larry

**Comment by workingDog** [comment]
Hi Larry,

I guess you are asking for a horizontal scrolling of the
calendar, then this is one way you could start.

In RKManager add: 
@Published var isVertical = true    (or false) 


In RKViewController:

replace:

//            RKWeekdayHeader(rkManager: self.rkManager).padding(.top, 15)
//            Divider()
//            List {
//                ForEach(0..<numberOfMonths()) { index in
//                    RKMonth(isPresented: self.$isPresented, rkManager: self.rkManager, monthOffset: index)
//                }
//                Divider()
//            }
 
with:
            
            rkManager.isVertical ?
                AnyView(Group {
                    RKWeekdayHeader(rkManager: self.rkManager)
                    Divider()
                    List {
                        ForEach(0..<numberOfMonths()) { index in
                            RKMonth(isPresented: self.$isPresented, rkManager: self.rkManager, monthOffset: index)
                        }
                        Divider()
                    }
                })
                :
                AnyView(ScrollView (.horizontal) {
                    HStack {
                        ForEach(0..<numberOfMonths()) { index in
                            VStack {
                                RKWeekdayHeader(rkManager: self.rkManager)
                                RKMonth(isPresented: self.$isPresented, rkManager: self.rkManager, monthOffset: index)
                            }
                            Divider()
                        }
                    }
                })
                              
                
I will not put this in my code for the moment because it is not polished enough.

Hope it helps.

Ringo

**Comment by workingDog** [comment]
it looks a bit better if you use:

                   AnyView(ScrollView (.horizontal) {
                    HStack {
                        ForEach(0..<numberOfMonths()) { index in
                            VStack {
                                RKWeekdayHeader(rkManager: self.rkManager)
                                Divider()
                                RKMonth(isPresented: self.$isPresented, rkManager: self.rkManager, monthOffset: index)
                                Spacer()
                            }
                            Divider()
                        }
                    }
                })

**Comment by lburris57** [comment]
I can’t thank you enough for the help!  I’ll try this and let you know!  Your calendar code is awesome!

**Comment by workingDog** [comment]
Hi Larry,

I've updated my calendar code to include an horizontal view and a few other bits, see the examples.
      https://github.com/workingDog/RKCalendar
Let me know if this works.

**Comment by lburris57** [comment]
Hi Ringo,

I am having issues with the code compiling.  It complains that it can’t find the files located in the ClockPicker directory although they are clearly there.  I simply cloned the file from GitHub and tried to build and run it.  I’m not quite sure what the problem might be.

I want to thank you very much for taking the time and effort to add these capabilities!

Larry

**Comment by lburris57** [comment]
Hi Ringo,

It turns out that all I had to do was to remove the ClockPicker directory and everything works fine.  However, I have the same problem in the fact that the calendars overlap in the screen instead of showing a single calendar per screen.  I think that I have solved my problem in a different way.

I changed the code to only display a single calendar at a time and I added Previous and Next buttons which will allow the user to display one calendar view at a time in either direction.  Of course, I need to write the code to make that happen and to only display the buttons when it makes sense but I believe that this is the functionality that would work best for me.

I can show you my solution along with the code once I have completed it if you are interested.  There’s a screen shot below...

Again, I can’t thank you enough for taking the time and effort to help me with my project!!

Larry

**Comment by workingDog** [comment]
Hi Larry,

I'm glad you got the code working, maybe for some reason the ClockPicker was included in 
the code update.

As I understand SwiftUI ScrollView does not yet have the capability to do paging that 
allows one "page" to be display at one time. Maybe the next version of SwiftUI will have that feature.

I would be interested in your code once you have it working. 

I could not see the screenshot.

Ringo

**Comment by workingDog** [comment]
Hi Larry,

I've added a number of things to the code, including a paging function to display one month at a time, both for vertical and horizontal scrolling.

Let me know if this works for you.

Ringo

**Comment by lburris57** [comment]
Hi Ringo,

Might be a few days. Crushed one of my fingers in a hinged adjustable bed yesterday morning. Hand in a soft cast. No one ever accused me of being graceful!

I will check it out soon. Thanks again for all your help. 

Larry

**Comment by lburris57** [comment]
Hey Ringo,

That’s EXACTLY what I was looking for!  Thanks for all your help!

Larry

**Pull request merged**
